package Ulead.Ejemplo3;

public class Donkey { 
	
	// ESTO ES UNA EXPLICACIÓN DEL LIBRO, EN DONDE HACE ENFASIS EN LA EQUIVALENCIA DE CLASES PADRES
	// ESTA CLASE ES EQUIVALENTE A LA CLASE DONKEY1 Y DONKEY2

}
