package Ulead.clasesAbstractas;

public abstract class Animal { // PARA QUE LOS METODOS SEAN ABSTRACTOS, LA CLASE DEBE SER ABSTRACTA

	// PARA QUE UNA CLASE SEA ABSTRACTA, DEBE SER PADRE DE OTRAS CLASES
	// EL FINAL NO ES PERMITDO, YA QUE LA CLASE DEBE EXTENDERSE A OTRAS
	// EL METODO ABSTRACTO NO PUEDE ESTAR EN PRIVATE
	// LAS CLASES ABSTRACTAS NO SE PUEDEN INSTANCIAR
	// TODAS LAS CLASES QUE HEREDAN LOS METODOS DE UNA ABSTRACTA, DEBE LLAMAR A ESOS METODOS
	
	protected int age;

	public void eat() {
		System.out.println("Animal is eating");
	}

	public abstract String getName();

}
